{
  "type": "record",
  "name": "DocumentType",
  "namespace": "io.xregistry",
  "fields": [
    {
      "name": "genericRecordDefinition",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "GenericRecord",
          "fields": [
            {
              "name": "object",
              "type": {
                "type": "map",
                "values": [
                  "null",
                  "boolean",
                  "int",
                  "long",
                  "float",
                  "double",
                  "bytes",
                  "string",
                  {
                    "type": "array",
                    "items": [
                      "null",
                      "boolean",
                      "int",
                      "long",
                      "float",
                      "double",
                      "bytes",
                      "string",
                      "io.xregistry.GenericRecord"
                    ]
                  },
                  "io.xregistry.GenericRecord"
                ]
              }
            }
          ]
        }
      },
      "default": [],
      "doc": "Internal field to define GenericRecord type for use in extension attributes"
    },
    {
      "name": "thingdescriptiongroups",
      "type": {
        "type": "map",
        "values": {
          "type": "record",
          "name": "ThingdescriptiongroupType",
          "fields": [
            {
              "name": "thingdescriptiongroupid",
              "type": "string",
              "description": "ID of the thingdescriptiongroup object"
            },
            {
              "name": "name",
              "type": [
                "string",
                "null"
              ],
              "doc": "Name of the object"
            },
            {
              "name": "epoch",
              "type": [
                "int",
                "null"
              ],
              "doc": "Epoch time of the object creation"
            },
            {
              "name": "self",
              "type": "string",
              "doc": "URL of the object"
            },
            {
              "name": "xid",
              "type": "string",
              "doc": "XID of the object"
            },
            {
              "name": "description",
              "type": [
                "string",
                "null"
              ],
              "doc": "Description of the object"
            },
            {
              "name": "documentation",
              "type": [
                "string",
                "null"
              ],
              "doc": "URI of the documentation of the object"
            },
            {
              "name": "labels",
              "type": {
                "type": "map",
                "values": [
                  "string",
                  "null"
                ]
              },
              "doc": "Labels for the object"
            },
            {
              "name": "createdat",
              "type": [
                {
                  "type": "int",
                  "logicalType": "time-millis"
                },
                "null"
              ],
              "doc": "Time of the object creation"
            },
            {
              "name": "modifiedat",
              "type": [
                {
                  "type": "int",
                  "logicalType": "time-millis"
                },
                "null"
              ],
              "doc": "Time of the object modification"
            },
            {
              "name": "Extensions",
              "type": {
                "type": "map",
                "name": "ExtensionsType",
                "default": {},
                "values": "io.xregistry.GenericRecord"
              }
            },
            {
              "name": "thingdescriptions",
              "type": {
                "type": "map",
                "values": {
                  "type": "record",
                  "name": "ThingdescriptionType",
                  "namespace": "io.xregistry.thingdescriptiongroups",
                  "fields": [
                    {
                      "name": "thingdescriptionid",
                      "type": "string",
                      "description": "ID of the thingdescription object"
                    },
                    {
                      "name": "name",
                      "type": [
                        "string",
                        "null"
                      ],
                      "doc": "Name of the object"
                    },
                    {
                      "name": "epoch",
                      "type": [
                        "int",
                        "null"
                      ],
                      "doc": "Epoch time of the object creation"
                    },
                    {
                      "name": "self",
                      "type": "string",
                      "doc": "URL of the object"
                    },
                    {
                      "name": "xid",
                      "type": "string",
                      "doc": "XID of the object"
                    },
                    {
                      "name": "description",
                      "type": [
                        "string",
                        "null"
                      ],
                      "doc": "Description of the object"
                    },
                    {
                      "name": "documentation",
                      "type": [
                        "string",
                        "null"
                      ],
                      "doc": "URI of the documentation of the object"
                    },
                    {
                      "name": "labels",
                      "type": {
                        "type": "map",
                        "values": [
                          "string",
                          "null"
                        ]
                      },
                      "doc": "Labels for the object"
                    },
                    {
                      "name": "createdat",
                      "type": [
                        {
                          "type": "int",
                          "logicalType": "time-millis"
                        },
                        "null"
                      ],
                      "doc": "Time of the object creation"
                    },
                    {
                      "name": "modifiedat",
                      "type": [
                        {
                          "type": "int",
                          "logicalType": "time-millis"
                        },
                        "null"
                      ],
                      "doc": "Time of the object modification"
                    },
                    {
                      "type": "string",
                      "name": "format"
                    },
                    {
                      "name": "Extensions",
                      "type": {
                        "type": "map",
                        "name": "ExtensionsType",
                        "default": {},
                        "values": "io.xregistry.GenericRecord"
                      }
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    {
      "name": "thingmodelgroups",
      "type": {
        "type": "map",
        "values": {
          "type": "record",
          "name": "ThingmodelgroupType",
          "fields": [
            {
              "name": "thingmodelgroupid",
              "type": "string",
              "description": "ID of the thingmodelgroup object"
            },
            {
              "name": "name",
              "type": [
                "string",
                "null"
              ],
              "doc": "Name of the object"
            },
            {
              "name": "epoch",
              "type": [
                "int",
                "null"
              ],
              "doc": "Epoch time of the object creation"
            },
            {
              "name": "self",
              "type": "string",
              "doc": "URL of the object"
            },
            {
              "name": "xid",
              "type": "string",
              "doc": "XID of the object"
            },
            {
              "name": "description",
              "type": [
                "string",
                "null"
              ],
              "doc": "Description of the object"
            },
            {
              "name": "documentation",
              "type": [
                "string",
                "null"
              ],
              "doc": "URI of the documentation of the object"
            },
            {
              "name": "labels",
              "type": {
                "type": "map",
                "values": [
                  "string",
                  "null"
                ]
              },
              "doc": "Labels for the object"
            },
            {
              "name": "createdat",
              "type": [
                {
                  "type": "int",
                  "logicalType": "time-millis"
                },
                "null"
              ],
              "doc": "Time of the object creation"
            },
            {
              "name": "modifiedat",
              "type": [
                {
                  "type": "int",
                  "logicalType": "time-millis"
                },
                "null"
              ],
              "doc": "Time of the object modification"
            },
            {
              "name": "Extensions",
              "type": {
                "type": "map",
                "name": "ExtensionsType",
                "default": {},
                "values": "io.xregistry.GenericRecord"
              }
            },
            {
              "name": "thingmodels",
              "type": {
                "type": "map",
                "values": {
                  "type": "record",
                  "name": "ThingmodelType",
                  "namespace": "io.xregistry.thingmodelgroups",
                  "fields": [
                    {
                      "name": "thingmodelid",
                      "type": "string",
                      "description": "ID of the thingmodel object"
                    },
                    {
                      "name": "name",
                      "type": [
                        "string",
                        "null"
                      ],
                      "doc": "Name of the object"
                    },
                    {
                      "name": "epoch",
                      "type": [
                        "int",
                        "null"
                      ],
                      "doc": "Epoch time of the object creation"
                    },
                    {
                      "name": "self",
                      "type": "string",
                      "doc": "URL of the object"
                    },
                    {
                      "name": "xid",
                      "type": "string",
                      "doc": "XID of the object"
                    },
                    {
                      "name": "description",
                      "type": [
                        "string",
                        "null"
                      ],
                      "doc": "Description of the object"
                    },
                    {
                      "name": "documentation",
                      "type": [
                        "string",
                        "null"
                      ],
                      "doc": "URI of the documentation of the object"
                    },
                    {
                      "name": "labels",
                      "type": {
                        "type": "map",
                        "values": [
                          "string",
                          "null"
                        ]
                      },
                      "doc": "Labels for the object"
                    },
                    {
                      "name": "createdat",
                      "type": [
                        {
                          "type": "int",
                          "logicalType": "time-millis"
                        },
                        "null"
                      ],
                      "doc": "Time of the object creation"
                    },
                    {
                      "name": "modifiedat",
                      "type": [
                        {
                          "type": "int",
                          "logicalType": "time-millis"
                        },
                        "null"
                      ],
                      "doc": "Time of the object modification"
                    },
                    {
                      "type": "string",
                      "name": "format"
                    },
                    {
                      "name": "Extensions",
                      "type": {
                        "type": "map",
                        "name": "ExtensionsType",
                        "default": {},
                        "values": "io.xregistry.GenericRecord"
                      }
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    }
  ]
}