#!/bin/bash

set -e

function clean() {
    set +e
    echo "# Stopping server"
    docker rm -f xrserver > /dev/null
}

badPatterns=(
  "required.*false"
  "hasdoc.*true"
  "plural"
)

trap clean EXIT

export XR_IMAGE=ghcr.io/xregistry/xr
export XRSERVER_IMAGE=ghcr.io/xregistry/xrserver-all
export XR_SERVER=http://localhost:8383

export XR="xr"

if ! which xr > /dev/null 2>&1 ; then
  export XR="docker run -i --network=host -v .:/spec -w /spec \
    $XR_IMAGE -s localhost:8383"
fi

# Start an xrserver to test loading the models and sample data
echo -n "# Starting xrserver"
docker run -qdti --name xrserver -p 8383:8080 $XRSERVER_IMAGE \
    --rootapp=xreg > /dev/null

while ! curl --silent --fail $XR_SERVER > /dev/null;do echo -n . && sleep 2;done
echo ; echo

# Validate all model.json files in the entire repo
for fn in `find . -name \*model.json`; do
    echo "# Model: $fn"
    echo "  # Verifying"
    $XR model verify $fn

    # Look for anti-patterns in the model
    for pattern in "${badPatterns[@]}" ; do
        if ( grep "$pattern" "$fn" > /dev/null ); then
            echo Found "'$pattern'"
            exit 1
        fi
    done

    echo "  # Loading"
    $XR model update $fn

    dir=$(dirname $fn)
    echo "  # Looking for samples (*.xreg.json) in: $dir"
    for data in `find $dir -name \*xreg.json`; do
        echo "  # Sample: $data"
        $XR update / -d @$data
    done

    list=$($XR model group list | grep -v GROUP | sed "s/\/.*//g")
    list=$(echo $list)
    if [[ "$list" != "" ]]; then
        echo "  # Deleting group instances: $list"
        $XR delete $list
        echo "  # Deleting group models: $list"
        $XR model group delete $list
    fi

echo
done

