#!/bin/bash

# 'words' from:
# https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt
# If you add words, add them to 'tools/dict'

set -e

for f in $* ; do
  echo "> $f"

  # assume "#..." are fragment pointers so ignore all words after the #
  sed "s/\(#\?[a-zA-Z0-9]\+\)/\n\1\n/gI" < $f | \
    tr '[:upper:]' '[:lower:]' | \
    sort -iu | \
    grep "^[a-z]" | \
    grep -v "[0-9]" > specwords
  sort -u tools/words tools/dict > words
  comm -23 specwords words > extra
  wc -l extra | grep "^0 extra" > /dev/null || \
	( echo -e "\nMISSPELLED (add to 'tools/dict'?):" ; cat extra ; exit 1 )
  rm specwords words extra

done
