on:
  push:
    branches:
      - main

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send event to xreg.io repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.XREGIO_PAT }}" \
          https://api.github.com/repos/xregistry/xregistry.github.io/dispatches \
          -d '{"event_type": "main_branch_updated"}'
